[workspace]
channels = ["conda-forge"]
name = "quiz-application"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.10,<3.12"
tesseract = "*"
pytesseract = "*"
numpy = "*"
opencv = "*"
fastapi = "*"
uvicorn = "*"