name: first_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  get: 4.6.6
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2
  flash_card: ^0.0.5
  hive_ce: 2.5.0+2
  hive_ce_flutter: 2.0.0
  camera: ^0.11.1
  path_provider: ^2.1.5
  path: ^1.9.1
  file_picker: ^10.2.0
  http: 1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  test: ^1.16.0

flutter:
  uses-material-design: true